# Generated by Django 4.2.8 on 2023-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_lead_phoned_lead_date_added_lead_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
