# Generated by Django 4.2.8 on 2023-12-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_user_destination_assign_alter_user_is_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organisation',
        ),
    ]
