# Generated by Django 4.2.8 on 2024-01-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_lead_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
