# Generated by Django 4.2.8 on 2024-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_agent_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='agent_full_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
