# Generated by Django 4.2.8 on 2024-01-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_remove_agent_full_name_user_agent_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='lead',
            name='destination',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
