# Generated by Django 4.2.8 on 2024-01-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_remove_lead_descriptions_lead_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='destination',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
