# Generated by Django 4.2.8 on 2024-01-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('leads', '0022_agent_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='destination_assign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.destination'),
        ),
    ]
