# Generated by Django 4.2.8 on 2024-01-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_remove_agent_destination_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
