# Generated by Django 4.2.8 on 2023-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('place_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('place_description', models.TextField(max_length=200)),
                ('place_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=10)),
            ],
        ),
    ]
