# Generated by Django 4.2.8 on 2024-01-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='place_picture',
            field=models.ImageField(blank=True, default='media_root/moun.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
