# Generated by Django 4.2.8 on 2024-01-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_place_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='place_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
